### ISSUE TITLE
libffi were not met

### ISSUE THREAD

**Issue by suhanyujie** [amaccis/docker-php-libstemmer#1]
Hello, Sir. When I tried to create this Dockerfile, it responded to give me some errors. Details of the error are as follows:

```
checking if zts is enabled... no
checking for gawk... no
checking for nawk... no
checking for awk... awk
checking if awk is broken... no
checking for FFI support... yes, shared
checking for libffi >= 3.0.11... no
configure: error: Package requirements (libffi >= 3.0.11) were not met:

Package 'libffi', required by 'virtual:world', not found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables FFI_CFLAGS
and FFI_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
The command '/bin/sh -c apk add libffi             libffi-dev;     docker-php-ext-install ffi' returned a non-zero code: 1
```

### env
- MacOS

### docker version
- Docker version 19.03.5, build 633a0ea

**Comment by amaccis** [comment]
Hi @suhanyujie.
You mean when you tried to build the image from the Dockerfile?
I just tried to rebuild the image (docker build -t amaccis/php-libstemmer .) and I got no errors. 
My env is the same as yours (MacOs Catalina and Docker 19.03.5)
Can you please provide me more details?

**Comment by amaccis** [comment]
Hi @suhanyujie 
You probably already solved this issue so I'm closing it.
If not, feel free to reopen it.
